commands:
  - desc: push_imm
    opcode: "0x01"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_b, add]
          - unit: cpu
            signals: [load_imm, push_stack]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: lw_from_imm_addr
    opcode: "0x02"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_b, add]
          - unit: mem
            signals: [read]
          - unit: cpu
            signals: [load_imm]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: lw_from_a_addr
    opcode: "0x03"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_a, add]
          - unit: mem
            signals: [read]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: lw_from_b_addr
    opcode: "0x04"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_b, add]
          - unit: mem
            signals: [read]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: lw_from_a_addr_inc_a
    opcode: "0x05"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_a, add]
          - unit: mem
            signals: [read]
      - signals:
          - unit: alu
            signals: [open_a, inc]
          - unit: cpu
            signals: [push_stack]
      - signals:
          - unit: cpu
            signals: [load_T_a, pop_stack]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: load_T_a_pop
    opcode: "0x06"
    micro_commands:
      - signals:
          - unit: cpu
            signals: [load_T_a, pop_stack]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: load_T_b_push
    opcode: "0x07"
    micro_commands:
      - signals:
          - unit: cpu
            signals: [load_T_b]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: dup
    opcode: "0x08"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_b, add]
          - unit: cpu
            signals: [load_T_b, push_stack]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: sw_to_imm_addr
    opcode: "0x10"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_b, add]
          - unit: mem
            signals: [write]
          - unit: cpu
            signals: [load_imm]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: sw_to_a_addr
    opcode: "0x11"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_a, add]
          - unit: mem
            signals: [write]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: sw_to_b_addr
    opcode: "0x12"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_b, add]
          - unit: mem
            signals: [write]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: sw_to_a_addr_inc_a
    opcode: "0x13"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_a, add]
          - unit: mem
            signals: [write]
      - signals:
          - unit: alu
            signals: [open_a, inc]
          - unit: cpu
            signals: [push_stack]
      - signals:
          - unit: cpu
            signals: [load_T_a, pop_stack]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: push_a
    opcode: "0x14"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_a, add]
          - unit: cpu
            signals: [push_stack]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: push_a_inc
    opcode: "0x15"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_a, add ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: alu
            signals: [ open_a, inc ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: cpu
            signals: [ load_T_a, pop_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: pop
    opcode: "0x16"
    micro_commands:
      - signals:
          - unit: cpu
            signals: [ pop_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: push_b
    opcode: "0x17"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_b, add ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: "+"
    opcode: "0x20"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_l, open_r, add ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: "-"
    opcode: "0x21"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_l, open_r, sub ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: "*"
    opcode: "0x22"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_l, open_r, mul ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: "/"
    opcode: "0x23"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_l, open_r, div ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: "<<"
    opcode: "0x24"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_l, shl ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: ">>"
    opcode: "0x25"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_l, shr ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: not
    opcode: "0x26"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_l, not ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: and
    opcode: "0x28"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_l, open_r, and ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: or
    opcode: "0x29"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_l, open_r, or ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: inc
    opcode: "0x2A"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_l, inc ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: over
    opcode: "0x30"
    micro_commands:
      - signals:
          - unit: cpu
            signals: [ over ]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: jmp
    opcode: "0x40"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_r_pc, open_b, add]
          - unit: cpu
            signals: [load_imm, fetch_pc]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: call
    opcode: "0x41"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_r_pc, open_b, add]
          - unit: cpu
            signals: [load_imm, call]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: ret
    opcode: "0x42"
    micro_commands:
      - signals:
          - unit: cpu
            signals: [restore_pc]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: if
    opcode: "0x43"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_r_pc, open_b, add, if]
          - unit: cpu
            signals: [load_imm, fetch_pc, pop_stack]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: "-if"
    opcode: "0x44"
    micro_commands:
      - signals:
          - unit: alu
            signals: [open_r_pc, open_b, add, -if]
          - unit: cpu
            signals: [load_imm, fetch_pc, pop_stack]
      - signals:
          - unit: micro_command
            signals: [term_mc]
  - desc: halt
    opcode: "0x45"
    micro_commands:
      - signals:
          - unit: cpu
            signals: [kill_cpu]
      - signals:
          - unit: micro_command
            signals: [term_mc]

  - desc: v_lw_from_imm_addr  # загрузка в стек векторов по адресу переданному команде
    opcode: "0x80"
    micro_commands:
      - signals:
            - unit: cpu
              signals: [ load_imm ]
            - unit: alu
              signals: [ open_b, add ]
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: mem
            signals: [ read ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: v_lw_from_a_addr  # загрузка в стек векторов по адресу в регистре a
    opcode: "0x81"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_a, add ]
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: mem
            signals: [ read ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: v_lw_from_b_addr  # загрузка в стек векторов по адрессу в регистре b
    opcode: "0x82"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_b, add ]
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: mem
            signals: [ read ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]

  - desc: v_sw_to_imm_addr  # запись верха стека векторов по адрессу переданному команде
    opcode: "0x90"
    micro_commands:
      - signals:
          - unit: cpu
            signals: [ load_imm ]
          - unit: alu
            signals: [ open_b, add ]
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: mem
            signals: [ write ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: v_sw_to_a_addr  # запись верха стека векторов по адрессу в регистре а
    opcode: "0x91"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_a, add ]
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: mem
            signals: [ write ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: v_sw_to_b_addr  # запись верха стека векторов по адрессу в регистре b
    opcode: "0x92"
    micro_commands:
      - signals:
          - unit: alu
            signals: [ open_b, add ]
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: mem
            signals: [ write ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: v_pop
    opcode: "0x93"
    micro_commands:
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: cpu
            signals: [ pop_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]

  - desc: "v+"  # сложение 2 верхних значений стека векторов
    opcode: "0xA0"
    micro_commands:
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: alu
            signals: [ open_l, open_r, add ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: "v-"  # вычитание 2 верхних значений стека векторов
    opcode: "0xA1"
    micro_commands:
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: alu
            signals: [ open_l, open_r, sub ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: "v*"  # умножение 2 верхних значений стека векторов
    opcode: "0xA2"
    micro_commands:
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: alu
            signals: [ open_l, open_r, mul ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: "v/"  # деление 2 верхних значений стека векторов
    opcode: "0xA3"
    micro_commands:
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: alu
            signals: [ open_l, open_r, div ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: "v<<"  # сдвиг в лево верха стека векторов
    opcode: "0xA4"
    micro_commands:
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: alu
            signals: [ open_l, open_r, shl ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: "v>>"  # сдвиг в право верха стека векторов
    opcode: "0xA5"
    micro_commands:
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: alu
            signals: [ open_l, open_r, shr ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: v_not  # побитовое отрицание верха стека векторов
    opcode: "0xA6"
    micro_commands:
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: alu
            signals: [ open_l, open_r, not ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: v_and  # побитовое "и" 2 верхних значений стека векторов
    opcode: "0xA8"
    micro_commands:
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: alu
            signals: [ open_l, open_r, and ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: v_or  # побитовое "или" 2 верхних значений стека векторов
    opcode: "0xA9"
    micro_commands:
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: alu
            signals: [ open_l, open_r, or ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: v_inc  # инкрементация верхнего значения стека векторов
    opcode: "0xAA"
    micro_commands:
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: alu
            signals: [ open_l, open_r, inc ]
          - unit: cpu
            signals: [ push_stack ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]
  - desc: v_over  # инкрементация верхнего значения стека векторов
    opcode: "0xB0"
    micro_commands:
      - signals:
          - unit: type
            signals: [ simd ]
          - unit: cpu
            signals: [ over ]
      - signals:
          - unit: micro_command
            signals: [ term_mc ]


