name: Emulator and compiler tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt

    - name: Run mypy
      run: |
        mypy .

    - name: Run ruff
      run: |
        ruff check . --output-format=github

    - name: Check ruff format
      run: |
        ruff format --check .

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Run golden tests
      run: |
        pytest -v tests/

  build-linux:
    needs: test
    runs-on: ubuntu-latest
    name: Build Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3.12-dev python3.12-venv upx
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller .github/workflows/stack-machine-linux.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stack-machine-linux
          path: dist/stack-machine/

  build-windows:
    needs: test
    runs-on: windows-latest
    name: Build Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .github/workflows/pyinstaller

      - name: Build with PyInstaller (Windows)
        run: pyinstaller stack-machine.spec

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: stack-machine-windows
          path: dist/stack-machine/